# Data Preprocessing Basics

In this notebook, we will prepare our dataset for Machine Learning:
1. Import libraries
2. Import dataset
3. Handle missing data
4. Encode categorical variables
5. Split into training and test sets
6. Feature scaling


### 1. Import libraries

In [1]:
# 1. Import necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### 2. Import dataset

In [9]:
# 2. Import dataset
dataset = pd.read_csv('../Dataset/Data.csv')

# -----------------------------------------------------------
# Features vs Dependent Variable
#
# In this dataset:
# - Features (independent variables) are:
#       Country, Age, Salary
#   These are the inputs (the information we know).
#
# - Dependent variable (target) is:
#       Purchased
#   This is the output we want to predict.
#
# The goal:
# Given Country, Age and Salary, can we predict whether
# the person purchased (Yes/No)?
# -----------------------------------------------------------

x = dataset.iloc[:, :-1].values  # Features (independent variables)
y = dataset.iloc[:, -1].values   # Dependent variable (target)


In [ ]:
# show the features.
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
# shpow the dependent variable.
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


### 3. Handle missing data

In [13]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')


# Fit the imputer to the features (independent variables)
imputer.fit(x[:, 1:3])  # Only apply to Age and Salary columns
# Transform the features to fill missing values
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [17]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


### 4. Encode categorical variables

In [ ]:
# 4. Encode categorical variables independent variables
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(), [0])  # Apply OneHotEncoder to the first column (Country)
    ],
    remainder='passthrough'  # Keep the other columns as they are
)

x = np.array(ct.fit_transform(x))

In [19]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [20]:
#encode categorical variables dependent variable
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)  # Encode 'Purchased' (Yes/No) as 1/0


In [21]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


### 5. Split into trainging and test sets

In [22]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=1
)

In [23]:
print(x_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [25]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [26]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [27]:
print(y_test)

[0 1]


### 6. Feature Scaling

In [28]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])  # Scale Age and Salary
x_test[:, 3:] = sc.transform(x_test[:, 3:])  # Scale

In [29]:
print(x_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [ ]:
print(x_test)                                                   

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
